#!/bin/sh
# $Id$
#
# ***** BEGIN GPL/BL DUAL LICENSE BLOCK *****
#
# The contents of this file may be used under the terms of either the GNU
# General Public License Version 2 or later (the "GPL", see
# http://www.gnu.org/licenses/gpl.html ), or the Blender License 1.0 or
# later (the "BL", see http://www.blender.org/BL/ ) which has to be
# bought from the Blender Foundation to become active, in which case the
# above mentioned GPL option does not apply.
#
# The Original Code is Copyright (C) 2002 by NaN Holding BV.
# All rights reserved.
#
# The Original Code is: all of this file.
#
# Contributor(s): none yet.
#
# ***** END GPL/BL DUAL LICENSE BLOCK *****
#
# usage example: cvsdiff   1.113     +2 -1      source/nan.mk
# note that the part after cvsdiff is just a pasted line from a commit mail

REV=$1
FILE=$4

REVBEGIN=`echo $REV | sed 's/\..*$/\./'`
REVEND=`echo $REV | sed 's/^.*\.//'`

PREVREVEND=`expr $REVEND - 1`
PREVREV=$REVBEGIN$PREVREVEND

cd $HOME/develop
cvs diff -r $PREVREV -r $REV $FILE
